// everything about students
// 1.form
export const STUDENT_FORM_SUBMIT_START = 'STUDENT_FORM_SUBMIT_START';
export const STUDENT_FORM_SUBMIT_SUCCESS = 'STUDENT_FORM_SUBMIT_SUCCESS';
export const STUDENT_FORM_SUBMIT_FAIL = 'STUDENT_FORM_SUBMIT_FAIL';
export const STUDENT_FORM_LOGO = 'STUDENT_FORM_LOGO';
export const STUDENT_FORM_BG = 'STUDENT_FORM_BG';
export const STUDENT_FORM_PDF = 'STUDENT_FORM_PDF';

// 2.student detail page
export const STUDENT_DETAIL_FETCH_START = 'STUDENT_DETAIL_FETCH_START';
export const STUDENT_DETAIL_FETCH_SUCCESS = 'STUDENT_DETAIL_FETCH_SUCCESS';
export const STUDENT_DETAIL_FETCH_FAIL = 'STUDENT_DETAIL_FETCH_FAIL';

// everything about companies
