// authentication
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

// everything about CENTERs
// 1.form
export const STUDENT_FORM_SUBMIT_START = 'STUDENT_FORM_SUBMIT_START';
export const STUDENT_FORM_SUBMIT_SUCCESS = 'STUDENT_FORM_SUBMIT_SUCCESS';
export const STUDENT_FORM_SUBMIT_FAIL = 'STUDENT_FORM_SUBMIT_FAIL';
export const STUDENT_FORM_LOGO = 'STUDENT_FORM_LOGO';
export const STUDENT_FORM_BG = 'STUDENT_FORM_BG';
export const STUDENT_FORM_PDF = 'STUDENT_FORM_PDF';

// 2.student detail page
export const STUDENT_DETAIL_FETCH_START = 'STUDENT_DETAIL_FETCH_START';
export const STUDENT_DETAIL_FETCH_SUCCESS = 'STUDENT_DETAIL_FETCH_SUCCESS';
export const STUDENT_DETAIL_FETCH_FAIL = 'STUDENT_DETAIL_FETCH_FAIL';

// everything about centers
// 1.form
export const CENTER_FORM_SUBMIT_START = 'CENTER_FORM_SUBMIT_START';
export const CENTER_FORM_SUBMIT_SUCCESS = 'CENTER_FORM_SUBMIT_SUCCESS';
export const CENTER_FORM_SUBMIT_FAIL = 'CENTER_FORM_SUBMIT_FAIL';
export const CENTER_FORM_LOGO = 'CENTER_FORM_LOGO';
export const CENTER_FORM_BG = 'CENTER_FORM_BG';
export const CENTER_FORM_PDF = 'CENTER_FORM_PDF';

// 2.CENTER detail page
export const CENTER_DETAIL_FETCH_START = 'CENTER_DETAIL_FETCH_START';
export const CENTER_DETAIL_FETCH_SUCCESS = 'CENTER_DETAIL_FETCH_SUCCESS';
export const CENTER_DETAIL_FETCH_FAIL = 'CENTER_DETAIL_FETCH_FAIL';
